### ISSUE TITLE
Limit included results

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/grunt-phantomas#145]
@drublic was pointing into the direction that the html pages get to heavy after certain amount of runs.

For that it would be nice to have a configurable limit to only include the latest x results.

@drublic What would be a reasonable default value? 50? 100?

**Comment by drublic** [comment]
Nice. I'll probably try to run this with our tests soon. Thanks.

**Comment by stefanjudis** [comment]
yeah - took a while. sorry for that. 

It's not released yet. One ticket missing in this milestone. :(
