### ISSUE TITLE
Filmstrip and Screenshopt doesn't render webfonts 

### ISSUE THREAD

**Issue by mpy-pixum** [stefanjudis/grunt-phantomas#149]
Hallo, i tried to measure my site with phantomas and the grunt plugin but the webfont doesn't render on the screenshots or the filmstrip plugin (.woff, .eot, .svg - google webfont loader)

Any suggestions? I already tried to use slimerjs (gecko) but everything seems pretty the same.

**Comment by stefanjudis** [comment]
Hey hey - this is definitely a problem on phantomas' side. @macbre

So it's you related with your other issues. :)

http://www.bbc.co.uk/blogs/internet/entries/a456cf81-a154-3082-a726-d13f4f28ee23

**Comment by stefanjudis** [comment]
macbre/phantomas#490 is closed.
