### ISSUE TITLE
Newest phantomas version

### ISSUE THREAD

**Issue by gfdickinson** [stefanjudis/grunt-phantomas#150]
I tried updating to the newest version of phantomas and ran into a problem with the way that the filmstrip images are named.  I can create a pull request if you are interested in updating to package.json entry for phantomas to 1.10.0.

**Comment by stefanjudis** [comment]
Cool! Thanks.

Will check out the PR. Do you need a quick release?

**Comment by gfdickinson** [comment]
No hurry, just wanted to save you the time that it took to figure out what was failing after the upgrade.

**Comment by stefanjudis** [comment]
Great!

Thanks a lot. :+1:
