### ISSUE TITLE
Gulp Plugin for phantomas

### ISSUE THREAD

**Issue by saalmaan** [stefanjudis/grunt-phantomas#157]
Hi All, 

Just a quick question, i see that you guys are enjoying phantomas as part of grunt, @stefanjudis are there any plans for porting this to gulp? (I have been exploring phantomas, would like to contribute too),  what are your thoughts?

Thanks

**Comment by stefanjudis** [comment]
Hey @saalmaan,

yeah for sure. :)

Actually this is on my long term todo list, but I haven't had time to remove all the grunt deps.

I think the perfect way would be to open an new repo (maybe `phantomas-ui` or something) and remove all the grunt deps there and then port it to gulp, broccoli, grunt, ... if needed.

Also `grunt-phantomas` is doing way too much stuff, so I'd go with two different tasks. Something like `buildSystemXX-phantomas` and `buildSystemXX-phantomas-ui`. But this is a long long term plan. :)

Removing deps shouldn't take that long (test coverage is really high, what makes it easier), but unfortunately I'm more into other projects at the moment. :( 

If you're up for it I can create this repo, copy stuff over and give you collab rights?

Surely feel free to fork or do anything you like with it. :bowtie:

**Comment by saalmaan** [comment]
Excellent, OK lets do it, :) I have managed to salvage code from grunt-plugin and run in gulp today :)
Some things were not really clear, like gruntWritefile and this whole promise thingy :) but I am sure you can help me on that. I like the idea of separating out the UI from core and this should allow faster development and updates to both. so what the next steps then? because if we want change the way phantomas works we have to create new repos ?

**Comment by stefanjudis** [comment]
Cool!!!

Yeah if you'd be up for it I'd create the repository `phantomas-ui` and would give you full access to it.

I'm totally up for discussions, code reviews or anything else you need. :)

Stuff like `grunt.writeFile` should be easily replaceable with `fs.writeFile` and all function are written in here https://github.com/gruntjs/grunt/tree/master/lib/grunt so it shouldn't be that complicated. :)

**Comment by saalmaan** [comment]
go ahead create that repo, just to be clear, this is just UI part? independent of build system? or this would be gulp centric?

**Comment by stefanjudis** [comment]
Exactly.

I made this mistake to be grunt dependent. 

When we want to port it to other build systems the project shouldn't care about the build system and deal with plan nodejs. :)

So the steps in my mind are (if you agree of course):

- copy project over to `phantomas-ui`
- remove grunt dep and expose module and cli functionality
- wrap it again with grunt, gulp, ...

**Comment by saalmaan** [comment]
OK Perfect, makes much more sense now. I will do some work today. feeling excited now :)

**Comment by stefanjudis** [comment]
Cool!

Thanks for jumping in. You're already collaborator in the new repository and a first issue is created.

I'd close this issue here for now and would go over to the other repo for further discussions. :bowtie: 

if that's fine for you?

**Comment by saalmaan** [comment]
yes, cool.
