### ISSUE TITLE
Not able to install on MAC

### ISSUE THREAD

**Issue by vikash-bhardwaj** [stefanjudis/grunt-phantomas#159]
Hi @stefanjudis ,

Sorry to disturb but I am not able to install this plug-in on my machine and for your information I am running on Node 5.6.0 and NPM 3.6.0. Is there some dependency I am missing before I install it or something?

Below error comes while I try to install, any help is much appreciated.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-phantomas" "--save-dev"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/vbhar2/.npm/slimerjs/0.9.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/vbhar2/.npm/slimerjs/0.9.5/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vbhar2/local/apache-tomcat-7.0.40/webapps/git/grunt-ci-toolkit/grunt-ci-toolkit/npm-debug.log

Thanks
Vikash Bhardwaj

**Comment by stefanjudis** [comment]
This is probably not a problem of `grunt-phantomas`. Can you try to execute `npm i phantomas` and tell me if the same error appears?

```
> npm install phantomas                                                                                           [13:04:30]
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/stefan/.nvm/v5.0.0/bin/node" "/Users/stefan/.nvm/v5.0.0/bin/npm" "install" "phantomas"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.2
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/stefan/.npm/slimerjs/0.9.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/stefan/.npm/slimerjs/0.9.5/package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefan/Sites/grunt-phantomas/npm-debug.log
FAIL: 1

stefan @ stefan-mac: ~/Sites/grunt-phantomas master (╯°□°)╯
> node --version
v5.0.0

stefan @ stefan-mac: ~/Sites/grunt-phantomas master (╯°□°)╯
> npm -v
3.5.2
```

It does here - which means the the issues should be files on phantomas'  side.

cc. @macbre

**Comment by HejdesGit** [comment]
If i'm not mistaken the latest Phantomas is using slimerjs 0.9.6 which does not have the same issue. https://github.com/macbre/phantomas/pull/585

**Comment by vikash-bhardwaj** [comment]
@stefanjudis, 'npm i phantomas' works fine with some warnings but no errors and process completes.

**Comment by stefanjudis** [comment]
@vikash-bhardwaj 

I published a new version with updated `phantomas` dep. Can you please try again?

**Comment by vikash-bhardwaj** [comment]
@stefanjudis Thanks for the info and after adding the latest version in package.json file it worked, somehow it was not working with old version.
