### ISSUE TITLE
252 Timeout when navigating to thetrainline.com

### ISSUE THREAD

**Issue by qashahin** [stefanjudis/grunt-phantomas#163]
Hi,

When navigating to 'https://www.thetrainline.com/' I get a 252 issue. Having looked through your issues I found that this may have been caused by a timeout.

When typing 'phantomas --url https://www.thetrainline.com/' on the command line I also get a 252 timeout issue however phantomas also provides all the data e.g

```
* requests: 140
* gzipRequests: 29
* postRequests: 0
* httpsRequests: 140
* notFound: 0
* bodySize: 1534495 bytes.....etc
```

I tried to increase the timeout in the Gruntfile however that did not help.

```
module.exports = function(grunt) {
    grunt.initConfig({
        phantomas: {
            site : {
                options : {
                    indexPath : './phantomas/',
                    options   : {
                        'timeout' : 160
                    },
                    url       : 'https://www.thetrainline.com/',
                    buildUi   : true,
                    numberOfRuns : 1
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-phantomas');
    grunt.registerTask('default', ['phantomas']);
};
```

When navigating to other sites such as Google the issue does not appear to present itself.

Can you provide some assistance please as to how I can resolve this? As said I tried to set the timeout to 30, 60, 120 and 160 as well as decrease the number of runs to 1 yet the 252 persists.

Best,
QAShahin

**Comment by stefanjudis** [comment]
I'll try to tackle a few open issues here on the weekend. :)

Feel free to remind me, in case I forgot. :)

**Comment by qashahin** [comment]
@stefanjudis Thank you very much. It would be great if you lend a hand with this.

**Comment by stefanjudis** [comment]
@qashahin 

I changed the behavior and it will now use metrics even when the runs fail.

This is a log against your site.

```
Running "phantomas:grunt" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
>> Phantomas execution failed with 252 but returned metrics.
>> Phantomas execution successful.
>> Phantomas execution failed with 252 but returned metrics.
>> Phantomas execution failed with 252 but returned metrics.
>> Phantomas execution successful.
>> 5 Phantomas execution(s) done -> checking results:
```

Will do some testing and then releasse a new version.

**Comment by stefanjudis** [comment]
Fixed with https://github.com/stefanjudis/grunt-phantomas/pull/165.

Let me know when you have further problems. Will release `v.0.13.0` now.

**Comment by qashahin** [comment]
@stefanjudis Thank you greatly for your time spent on this, this has really helped me a lot. I am forever grateful.
